"""
===============================================================================
2_decoder.py - 3D Model Generation from Voxel Data
===============================================================================

This script uses the Trellis pipeline to generate high-quality 3D models (GLB)
from voxel data produced by the VLM demo.

Pipeline Overview:
    1. Load the pre-trained Trellis Image-to-3D decoder pipeline
    2. For each processed demo image:
       - Load the original image and voxel coordinates
       - Create a sparse structure tensor from voxel data
       - Run the pipeline with the structure as a control signal
       - Export the result as a GLB file with textures

Key Concepts:
    - Sparse Structure (ss): A 64x64x64 binary tensor indicating occupied voxels
    - Voxel Coordinates: 32x32x32 grid coordinates that are upscaled to 64x64x64
    - Control Signal: The sparse structure guides the 3D generation process

Dependencies:
    - Trellis pipeline for 3D generation
    - Pre-trained decoder model in ./pretrain/decoder

Author: PhysX-Anything Team
===============================================================================
"""

# =============================================================================
# IMPORTS
# =============================================================================

import os

# Environment configuration (must be set before importing trellis)
# os.environ['ATTN_BACKEND'] = 'xformers'  # Alternative: 'flash-attn' (default)
os.environ['SPCONV_ALGO'] = 'native'  # 'native' is slower but avoids benchmarking overhead

# Trellis 3D generation pipeline
from trellis.pipelines import TrellisImageTo3DPipeline
from trellis.utils import render_utils, postprocessing_utils

# Image processing
import imageio
from PIL import Image

# Data processing
import numpy as np
import torch
import trimesh

# Debugging (can be removed in production)
import ipdb


# =============================================================================
# CONFIGURATION
# =============================================================================

# Voxel grid settings
VOXEL_GRID_SIZE = 32      # Size of VLM output voxel grid
SPARSE_RESOLUTION = 64    # Size of decoder's sparse structure tensor


# =============================================================================
# MAIN EXECUTION
# =============================================================================

# Load the Trellis Image-to-3D pipeline from pre-trained weights
print("Loading Trellis decoder pipeline...")
pipeline = TrellisImageTo3DPipeline.from_pretrained("./pretrain/decoder")
pipeline.cuda()
print("Pipeline loaded successfully!")

# Setup paths
basepath = './demo'           # Original demo images
filepath = './test_demo'      # VLM output directory (contains voxel data)
namelist = os.listdir(basepath)

print(f"Found {len(namelist)} images to process")

# =============================================================================
# Process Each Image
# =============================================================================

for name in namelist:
    print(f"\n{'='*60}")
    print(f"Processing: {name}")
    print('='*60)
    
    # Load the original image
    image = Image.open(os.path.join(basepath, name))
    
    # Path to VLM output for this image
    qwenpath = os.path.join(filepath, name[:-4])  # Remove file extension
    
    # Check if voxel data exists (generated by 1_vlm_demo.py)
    voxel_file = os.path.join(qwenpath, 'allind.npy')
    
    if os.path.exists(voxel_file):
        print("Loading voxel coordinates...")
        newcoords = np.load(voxel_file)
        print(f"  Loaded {len(newcoords)} voxel coordinates")
        
        # =====================================================================
        # Create Sparse Structure Tensor
        # =====================================================================
        # The voxel coordinates are in a 32x32x32 grid
        # We need to place them in a 64x64x64 tensor, centered
        
        size = VOXEL_GRID_SIZE        # Original voxel grid size (32)
        resolution = SPARSE_RESOLUTION # Target resolution (64)
        
        # Center the 32x32x32 voxels within the 64x64x64 grid
        # Offset = 32 - (32/2) = 32 - 16 = 16 (but current formula gives: 32 - 16 = 16)
        # This places voxels in the center region [16, 48) of each axis
        offset = resolution // 2 - size // 2  # = 32 - 16 = 16
        newcoords = newcoords + offset
        
        # Create empty sparse structure tensor
        # Shape: (1, batch) x (64, 64, 64) spatial dimensions
        ss = torch.zeros(1, resolution, resolution, resolution, dtype=torch.long)
        
        # Mark occupied voxels
        ss[:, newcoords[:, 0], newcoords[:, 1], newcoords[:, 2]] = 1
        
        # Convert to float tensor on GPU with proper shape for pipeline
        # Final shape: (1, 1, 64, 64, 64) - batch, channel, depth, height, width
        ss = ss.cuda().float().unsqueeze(0)
        
        print(f"  Created sparse structure tensor: {ss.shape}")
        print(f"  Occupied voxels: {ss.sum().item():.0f}")
        
        # =====================================================================
        # Run 3D Generation Pipeline
        # =====================================================================
        print("Running 3D generation pipeline...")
        
        # run_control uses the sparse structure as a conditioning signal
        # This guides the generation to match the predicted voxel structure
        outputs = pipeline.run_control(
            ss,           # Sparse structure control signal
            image,        # Original image for appearance/texture
            seed=1,       # Fixed seed for reproducibility
        )
        
        print("  Generation complete!")
        
        # =====================================================================
        # Export as GLB File
        # =====================================================================
        print("Exporting GLB file...")
        
        # Convert outputs to GLB format
        # - gaussian: 3D Gaussian splatting representation
        # - mesh: Triangle mesh representation
        glb = postprocessing_utils.to_glb(
            outputs['gaussian'][0],
            outputs['mesh'][0],
            simplify=0.5,       # Remove 50% of triangles for smaller file size
            texture_size=1024,  # Texture resolution
        )
        
        # Save the GLB file
        output_path = os.path.join(qwenpath, 'sample.glb')
        glb.export(output_path)
        
        print(f"  Saved: {output_path}")
    else:
        print(f"  Skipping: No voxel data found at {voxel_file}")
        print("  (Run 1_vlm_demo.py first to generate voxel data)")

print("\n" + "="*60)
print("Decoder processing complete!")
print("="*60)





